# Generated by Django 5.0.6 on 2024-08-23 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
                ('type', models.CharField(choices=[('L', 'LOG IN'), ('S', 'SIGN UP')], default='L', max_length=1)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
