# Generated by Django 5.0.6 on 2024-09-01 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otpauthentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpauthentication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 8, 34, 51, 216442, tzinfo=datetime.timezone.utc)),
        ),
    ]
