# Generated by Django 5.0.6 on 2024-09-01 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otpauthentication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpauthentication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
