# Generated by Django 5.0.6 on 2024-10-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_otpauthentication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.TextField(default='hellow this is a demo session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OtpAuthentication',
        ),
    ]
