# Generated by Django 5.0.6 on 2024-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_hash',
            field=models.TextField(default='alskdjf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='api_id',
            field=models.CharField(default='alskdjf', max_length=50),
            preserve_default=False,
        ),
    ]
