# Generated by Django 5.0.6 on 2024-10-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_api_hash_user_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
