# Generated by Django 5.0.6 on 2024-09-28 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramEntities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loadenedentitiy',
            name='label',
            field=models.CharField(choices=[('to', 'post_to'), ('fr', 'from')], default='to', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadenedentitiy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
